/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Doctor;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author podda
 */
public class DoctorRequestBloodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRequestBloodJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    private User userAccount;
    private Patient patient;

    public DoctorRequestBloodJPanel(JPanel userProcessContainer, User account, Ecosystem ecosystem, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = account;
        this.patient = patient;
        BloodRequestQuantityBox.addItem("Select Quantity");
        BloodRequestQuantityBox.addItem("1");
        BloodRequestQuantityBox.addItem("2");
        BloodRequestQuantityBox.addItem("3");
        BloodRequestQuantityBox.addItem("4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BloodRequestQuantityBox = new javax.swing.JComboBox<>();
        lblRequestBloodQuantity = new javax.swing.JLabel();
        btnProcessRequest = new javax.swing.JButton();
        Request1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 157, 144));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blood Appeal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 40, 1274, -1));

        BloodRequestQuantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodRequestQuantityBoxActionPerformed(evt);
            }
        });
        add(BloodRequestQuantityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 180, 40));

        lblRequestBloodQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lblRequestBloodQuantity.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblRequestBloodQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblRequestBloodQuantity.setText("Blood Packs :");
        add(lblRequestBloodQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 160, 40));

        btnProcessRequest.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnProcessRequest.setForeground(new java.awt.Color(202, 97, 71));
        btnProcessRequest.setText("Complete");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });
        add(btnProcessRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 197, 40));

        Request1.setBackground(new java.awt.Color(40, 157, 144));
        Request1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        Request1.setForeground(new java.awt.Color(255, 255, 255));
        Request1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icon_Button_transparent.png"))); // NOI18N
        Request1.setBorder(null);
        Request1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Request1ActionPerformed(evt);
            }
        });
        add(Request1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 42));
    }// </editor-fold>//GEN-END:initComponents

    private void BloodRequestQuantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodRequestQuantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodRequestQuantityBoxActionPerformed

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:

        if (!((String) BloodRequestQuantityBox.getSelectedItem()).equals("Select Quantity")) {

            patient.setpatient_BloodBankStatus("Requested");
            patient.setpatient_BloodBagQuantity((String) BloodRequestQuantityBox.getSelectedItem());
            
            JOptionPane.showMessageDialog(null, "Blood Request Sent", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            DoctorVisitJPanel doctorVisit = new DoctorVisitJPanel(userProcessContainer, userAccount, ecosystem, patient);
            userProcessContainer.add("Visit Doctor", doctorVisit);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void Request1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Request1ActionPerformed
        // TODO add your handling code here:
        DoctorVisitJPanel doctorVisit = new DoctorVisitJPanel(userProcessContainer, userAccount, ecosystem, patient);
        userProcessContainer.add("Visit Doctor", doctorVisit);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_Request1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BloodRequestQuantityBox;
    private javax.swing.JButton Request1;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRequestBloodQuantity;
    // End of variables declaration//GEN-END:variables
}
