/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Police;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikhilreddypolepally
 */
public class PoliceWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    JPanel userProcessContainer;
    User account;
    Ecosystem ecoSystem;
    public PoliceWorkAreaJPanel(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = business;
        this.account = account;
        populatePatientTable();
        populatePatientTable1();
    }
              private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpatient_FirstName();
            row[1] = patient.getpatient_LastName();           
            row[2] = patient.getpatient_HealthInsuranceID();
            row[3] = patient.getpatient_Age();
            row[4] = patient.getpatient_Address();
            row[5] = patient.getpatient_EmailAddress();
            row[6] = patient.getpatient_PoliceStatus();
            row[7] = patient;
            if(patient.getpatient_PoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
               private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable1.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpatient_FirstName();
            row[1] = patient.getpatient_LastName();
            row[2] = patient.getpatient_HealthInsuranceID();
            row[3] = patient.getpatient_Age();
            row[4] = patient.getpatient_Address();
            row[5] = patient.getpatient_EmailAddress();
            row[6] = patient.getpatient_PoliceStatus();
            row[7] = patient;
            if(!patient.getpatient_PoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        managePatientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        managePatientTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-police-64.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 70, 80));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Police Department");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 26, 590, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 1260, 30));

        managePatientTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        managePatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "HealthId", "Age", "Address", "Email", "Police Verification", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(managePatientTable);
        if (managePatientTable.getColumnModel().getColumnCount() > 0) {
            managePatientTable.getColumnModel().getColumn(7).setMinWidth(0);
            managePatientTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            managePatientTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1260, 140));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Verification Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 201, 320, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Past Records");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 310, 40));

        managePatientTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        managePatientTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "HealthId", "Age", "Address", "Email", "Police Verification", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(managePatientTable1);
        if (managePatientTable1.getColumnModel().getColumnCount() > 0) {
            managePatientTable1.getColumnModel().getColumn(7).setMinWidth(0);
            managePatientTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
            managePatientTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1260, 191));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(202, 97, 71));
        jButton1.setText("View Details of Verification");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 316, 37));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(202, 97, 71));
        jButton2.setText("View Details of Past Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 720, 320, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = managePatientTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            Patient d = (Patient) managePatientTable.getValueAt(selectedRow, 7);
            PersonInfo bill = new PersonInfo(userProcessContainer,ecoSystem, d,account);
            userProcessContainer.add("Police Person Info", bill);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                   
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = managePatientTable1.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            Patient d = (Patient) managePatientTable1.getValueAt(selectedRow, 7);
            //d.get
            PastInfo bill = new PastInfo(userProcessContainer,ecoSystem, d,account);
            userProcessContainer.add("Past Info", bill);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
                   
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managePatientTable;
    private javax.swing.JTable managePatientTable1;
    // End of variables declaration//GEN-END:variables
}
