/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ReceptionRole;


import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Patient.PatientBills;
import BusinessModel.UserAccount.User;
import BusinessUtil.Mail.SendMail;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UI.Ambulance.AmbulanceWorkAreaJPanel;
import UI.Ambulance.ReceptionAmbulanceWorkAreaJPanel;

/**
 *
 * @author nikhilreddypolepally
 */
public class ReceptionDischarge extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    private final JPanel userProcessContainer;
    private final Ecosystem ecoSystem;
    User userAccount;

    public ReceptionDischarge(JPanel userProcessContainer, User account, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = system;
        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) ManageCustomersTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getPatientDirectory().getPatientList()) {

            Object[] row = new Object[10];
            row[0] = patient.getpatient_FirstName();
            row[1] = patient.getpatient_LastName();
            row[2] = patient.getpatient_Gender();
            row[3] = patient.getpatient_HealthInsuranceID();
            row[4] = patient.getpatient_Age();
            row[5] = patient.getpatient_EmailAddress();
            row[6] = patient.getpatient_InsuranceStatus();
            row[7] = patient.getpatient_Status();
            row[8] = patient;
            if(patient.getpatient_Status().equals("Ready to Discharge")){
            model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManageCustomersTable = new javax.swing.JTable();
        btnUpdateAmbulanceRecord = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnUpdateAmbulanceRecord1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Discharge Patient");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 330, 70));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 1260, 10));

        ManageCustomersTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ManageCustomersTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ManageCustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "Gender", "HealthId", "Age", "Email", "Payment", " Patient Status", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ManageCustomersTable);
        if (ManageCustomersTable.getColumnModel().getColumnCount() > 0) {
            ManageCustomersTable.getColumnModel().getColumn(8).setMinWidth(0);
            ManageCustomersTable.getColumnModel().getColumn(8).setPreferredWidth(0);
            ManageCustomersTable.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 1190, 216));

        btnUpdateAmbulanceRecord.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnUpdateAmbulanceRecord.setForeground(new java.awt.Color(202, 97, 71));
        btnUpdateAmbulanceRecord.setText("Discharge");
        btnUpdateAmbulanceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAmbulanceRecordActionPerformed(evt);
            }
        });
        add(btnUpdateAmbulanceRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 140, 40));

        btnUpdate1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(202, 97, 71));
        btnUpdate1.setText("Verify Insurance Check");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 260, 40));

        btnUpdateAmbulanceRecord1.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdateAmbulanceRecord1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnUpdateAmbulanceRecord1.setForeground(new java.awt.Color(51, 51, 51));
        btnUpdateAmbulanceRecord1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/back.png"))); // NOI18N
        btnUpdateAmbulanceRecord1.setBorder(null);
        btnUpdateAmbulanceRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAmbulanceRecord1ActionPerformed(evt);
            }
        });
        add(btnUpdateAmbulanceRecord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateAmbulanceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAmbulanceRecordActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = ManageCustomersTable.getSelectedRow();
        if (selectedRowIndex < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            Patient patient = (Patient) ManageCustomersTable.getValueAt(selectedRowIndex, 8);
            int totalAmount = 0;
            for (PatientBills b : patient.getpatient_bills()) {
                totalAmount += b.getAmount();
            }
            if(patient.getpatient_InsuranceStatus().equals("Verifying Insurance")){
                JOptionPane.showMessageDialog(null, "Cannot discharge verifying insurance.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else if(patient.getpatient_InsuranceStatus().equals("Cash")||patient.getpatient_InsuranceStatus().equals("Rejected")){
                patient.setpatient_Status("Discharged");
                SendMail.sendMail(patient.getpatient_EmailAddress(), "Hello "+patient.getpatient_FirstName()+","+"\nCash Payment Processed. Total Bill Amount is :"+String.valueOf(totalAmount)+"\nThank you, \nInfirmary Management System.");
                JOptionPane.showMessageDialog(null, "Cash payment Received.Patient Discharged.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                patient.setpatient_Status("Discharged");
                SendMail.sendMail(patient.getpatient_EmailAddress(), "Hello "+patient.getpatient_FirstName()+","+"\nInsurance Payment Cleared. Total Bill Amount is :"+String.valueOf(totalAmount)+"\nThank you, \nInfirmary Management System.");
                JOptionPane.showMessageDialog(null, "Insurance payment Received.Patient Discharged.", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            //patient.setStatus("Insurance Verification");
            populateNetworkTable();
            //ManageCustomersTable doctorRequestLabTestJPanel = new ManageCustomersTable(userProcessContainer, userAccount,patient);
            //userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
            //CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            //layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnUpdateAmbulanceRecordActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        
              
        int selectedRowIndex = ManageCustomersTable.getSelectedRow();
        if (selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Patient patient = (Patient) ManageCustomersTable.getValueAt(selectedRowIndex, 8);

            if(patient.getpatient_InsuranceStatus().equals("Verifying Insurance")||patient.getpatient_InsuranceStatus().equals("Rejected")||patient.getpatient_InsuranceStatus().equals("Approved")){
                JOptionPane.showMessageDialog(null, "Already Verifying or verified", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else if(patient.getpatient_InsuranceStatus().equals("Cash")){
                JOptionPane.showMessageDialog(null, "Cash payment method is not eligible.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
                ecoSystem.getInsuranceDirectory().addServedCustomers(patient);
                patient.setpatient_InsuranceStatus("Verifying Insurance");
                patient.setpatient_PoliceStatus("Not Verified");
                try{
                    //ecoSystem.sendEmail("insurance.aed@zohomail.com", "Approval Request for "+ patient.get(), "Please verify insurance approval request of "+patient.get()+" "+patient.getpatient_LastName()+" Insurance ID "+patient.getpatient_HealthInsuranceID(), "hospital.aed@zohomail.com", "Bangbang@8899");
                    //ecoSystem.smsTwillio(patient.get()+" "+patient.getpatient_LastName());
                }
        catch(Exception e){}
                JOptionPane.showMessageDialog(null, "Sent to Insurance Approval", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
            //patient.setStatus("Insurance Verification");
            populateNetworkTable();
            //ManageCustomersTable doctorRequestLabTestJPanel = new ManageCustomersTable(userProcessContainer, userAccount,patient);
            //userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
            //CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            //layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnUpdateAmbulanceRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAmbulanceRecord1ActionPerformed
        // TODO add your handling code here:
        ReceptionWorkAreaJPanel patientBillJPanel = new ReceptionWorkAreaJPanel(userProcessContainer,userAccount,ecoSystem);
        userProcessContainer.add("Patient Bill", patientBillJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateAmbulanceRecord1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ManageCustomersTable;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdateAmbulanceRecord;
    private javax.swing.JButton btnUpdateAmbulanceRecord1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
